export type MarketRow = {
  produce: string
  market: string
  province: string
  location: string
  rangeLow: number
  rangeHigh: number
  average: number
  date: string
  source: string
}

export const provinces = [
  'All provinces',
  'Harare',
  'Bulawayo',
  'Manicaland',
  'Mashonaland Central',
  'Mashonaland East',
  'Mashonaland West',
  'Masvingo',
  'Matabeleland North',
  'Matabeleland South',
  'Midlands',
]

export const crops = [
  'All crops',
  'Maize',
  'Wheat',
  'Sunflower',
  'Soyabeans',
  'Finger Millet',
  'Pearl Millet',
  'Sorghum',
  'Groundnuts',
  'Cowpeas',
]

export const marketData: MarketRow[] = [
  {
    produce: 'Wheat',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 524.56,
    rangeHigh: 524.56,
    average: 524.56,
    date: '2026-04-29',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Sunflower',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 670.46,
    rangeHigh: 670.46,
    average: 670.46,
    date: '2026-04-14',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Soyabeans',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 583.01,
    rangeHigh: 583.01,
    average: 583.01,
    date: '2026-04-14',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Finger Millet',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 364.75,
    rangeHigh: 364.75,
    average: 364.75,
    date: '2026-04-14',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Pearl Millet',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 364.75,
    rangeHigh: 364.75,
    average: 364.75,
    date: '2026-04-14',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Sorghum',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 364.75,
    rangeHigh: 364.75,
    average: 364.75,
    date: '2026-04-14',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Maize',
    market: 'GMB National Producer Price',
    province: 'Harare',
    location: 'Harare Urban, Harare',
    rangeLow: 340.0,
    rangeHigh: 340.0,
    average: 340.0,
    date: '2026-04-14',
    source: 'Grain Marketing Board (GMB)',
  },
  {
    produce: 'Groundnuts',
    market: 'Mbare Musika Wholesale',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 720.0,
    rangeHigh: 850.0,
    average: 785.0,
    date: '2026-04-20',
    source: 'Mbare Musika (Wholesale)',
  },
  {
    produce: 'Cowpeas',
    market: 'Mbare Musika Wholesale',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 400.0,
    rangeHigh: 480.0,
    average: 440.0,
    date: '2026-04-20',
    source: 'Mbare Musika (Wholesale)',
  },
  {
    produce: 'Maize',
    market: 'Bulawayo Wholesale',
    province: 'Bulawayo',
    location: 'Bulawayo Urban, Bulawayo',
    rangeLow: 320.0,
    rangeHigh: 360.0,
    average: 340.0,
    date: '2026-04-18',
    source: 'Bulawayo Market Traders',
  },
  {
    produce: 'Groundnuts',
    market: 'Mutare Wholesale',
    province: 'Manicaland',
    location: 'Mutare Urban, Manicaland',
    rangeLow: 700.0,
    rangeHigh: 820.0,
    average: 760.0,
    date: '2026-04-22',
    source: 'Mutare Market Traders',
  },
  {
    produce: 'Sorghum',
    market: 'Masvingo Wholesale',
    province: 'Masvingo',
    location: 'Masvingo Urban, Masvingo',
    rangeLow: 350.0,
    rangeHigh: 380.0,
    average: 365.0,
    date: '2026-04-15',
    source: 'Masvingo Market Traders',
  },
]
