export type MarketRow = {
  produce: string
  market: string
  province: string
  location: string
  rangeLow: number
  rangeHigh: number
  average: number
  date: string
  source: string
  unit: string
}

export const provinces = [
  'All provinces',
  'Harare',
  'Bulawayo',
  'Manicaland',
  'Mashonaland Central',
  'Mashonaland East',
  'Mashonaland West',
  'Masvingo',
  'Matabeleland North',
  'Matabeleland South',
  'Midlands',
]

export const crops = [
  'All crops',
  // Field crops
  'Maize',
  'Wheat',
  'Sunflower',
  'Soyabeans',
  'Finger Millet',
  'Pearl Millet',
  'Sorghum',
  'Groundnuts',
  'Cowpeas',
  'Sugar beans',
  'Beans',
  'Nyemba',
  'Traditional Grains',
  // Horticulture
  'Butternuts',
  'Potatoes',
  'Onions',
  'Red onions',
  'Fresh onions',
  'Tomatoes',
  'Carrots',
  'Cucumber',
  'Peas',
  'Green beans',
  'Green Pepper',
  'Yellow pepper',
  'Cabbage',
  'Rape',
  'Covo',
  'Tsunga',
  'Okra',
  // Fruits
  'Orange',
  'Lemon',
  'Watermelon',
  'Fresh Masawu',
  'Mawuyu',
  // Other
  'Dried mushroom',
  'Nyimo (dried)',
  'Madora',
  'Matemba (carpenter)',
  'Zviyo (finger millet)',
  'Mapfunde (Sorghum)',
  'Mhunga (millet)',
  'Green mealies',
  'Mbambaira',
]

export const marketData: MarketRow[] = [
  // ---------- HORTICULTURE (Mbare Musika) ----------
  {
    produce: 'Butternuts',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 20,
    rangeHigh: 30,
    average: 25,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  {
    produce: 'Potatoes',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 4.5,
    rangeHigh: 8,
    average: 6.25,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per pocket',
  },
  {
    produce: 'Onions',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 4,
    rangeHigh: 6,
    average: 5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per pocket',
  },
  {
    produce: 'Red onions',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 12,
    rangeHigh: 15,
    average: 13.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per pocket',
  },
  {
    produce: 'Fresh onions',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 1,
    rangeHigh: 1.875,
    average: 1.4,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'for 8-15',
  },
  {
    produce: 'Tomatoes',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 12,
    rangeHigh: 12,
    average: 12,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per crown',
  },
  {
    produce: 'Tomatoes',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 6,
    rangeHigh: 10,
    average: 8,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per crate',
  },
  {
    produce: 'Tomatoes',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 1,
    rangeHigh: 2.5,
    average: 1.75,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per wooden box',
  },
  {
    produce: 'Carrots',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 20,
    rangeHigh: 25,
    average: 22.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  {
    produce: 'Cucumber',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 15,
    rangeHigh: 22,
    average: 18.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  {
    produce: 'Peas',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 15,
    rangeHigh: 20,
    average: 17.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  {
    produce: 'Green beans',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 15,
    rangeHigh: 15,
    average: 15,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  {
    produce: 'Green Pepper',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 20,
    rangeHigh: 25,
    average: 22.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  {
    produce: 'Cabbage',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 0.3,
    rangeHigh: 0.75,
    average: 0.525,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per head',
  },
  {
    produce: 'Rape',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 0.5,
    rangeHigh: 1,
    average: 0.75,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bundle',
  },
  {
    produce: 'Covo',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 1,
    rangeHigh: 2,
    average: 1.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bundle',
  },
  {
    produce: 'Tsunga',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 0.5,
    rangeHigh: 1,
    average: 0.75,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bundle',
  },
  {
    produce: 'Okra',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 1,
    rangeHigh: 1.5,
    average: 1.25,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per 5L',
  },
  {
    produce: 'Green mealies',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 2,
    rangeHigh: 3.5,
    average: 2.75,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per dozen',
  },
  {
    produce: 'Watermelon',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 1,
    rangeHigh: 5,
    average: 3,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per head',
  },
  {
    produce: 'Yellow pepper',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 2,
    rangeHigh: 2,
    average: 2,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per kg',
  },
  // ---------- FRUITS ----------
  {
    produce: 'Orange',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 3.5,
    rangeHigh: 5,
    average: 4.25,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per pocket',
  },
  {
    produce: 'Lemon',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 3,
    rangeHigh: 4,
    average: 3.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Fresh Masawu',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 1,
    rangeHigh: 2.5,
    average: 1.75,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per 5L',
  },
  {
    produce: 'Mawuyu',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 5,
    rangeHigh: 5,
    average: 5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  // ---------- LEGUMES & GRAINS ----------
  {
    produce: 'Sugar beans',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 22,
    rangeHigh: 26,
    average: 24,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Beans',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 24,
    rangeHigh: 26,
    average: 25,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Nyemba',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 12,
    rangeHigh: 16,
    average: 14,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Nzungu (groundnuts)',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 28,
    rangeHigh: 28,
    average: 28,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket (shelled)',
  },
  {
    produce: 'Nyimo (dried)',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 24,
    rangeHigh: 24,
    average: 24,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket (shelled)',
  },
  {
    produce: 'Zviyo (finger millet)',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 20,
    rangeHigh: 20,
    average: 20,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Mapfunde (Sorghum)',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 8,
    rangeHigh: 8,
    average: 8,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Mhunga (millet)',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 10,
    rangeHigh: 10,
    average: 10,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Soyabeans',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 8,
    rangeHigh: 8,
    average: 8,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  // ---------- OTHER ----------
  {
    produce: 'Dried mushroom',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 12,
    rangeHigh: 12,
    average: 12,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Madora',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 120,
    rangeHigh: 120,
    average: 120,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per bucket',
  },
  {
    produce: 'Matemba (carpenter)',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 8,
    rangeHigh: 13,
    average: 10.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per 5L',
  },
  {
    produce: 'Mbambaira',
    market: 'Mbare Musika',
    province: 'Harare',
    location: 'Mbare, Harare',
    rangeLow: 30,
    rangeHigh: 35,
    average: 32.5,
    date: '2026-09-26',
    source: 'Farmers.co.zw',
    unit: 'per Semea',
  },
  // ---------- GMB PRODUCER PRICES (2026/27 season) ----------
  {
    produce: 'Maize',
    market: 'GMB Producer Price',
    province: 'Harare',
    location: 'National (floor price)',
    rangeLow: 432,
    rangeHigh: 432,
    average: 432,
    date: '2026-09-10',
    source: 'Grain Marketing Board (GMB)',
    unit: 'per tonne',
  },
  {
    produce: 'Traditional Grains',
    market: 'GMB Producer Price',
    province: 'Harare',
    location: 'National (floor price)',
    rangeLow: 432,
    rangeHigh: 432,
    average: 432,
    date: '2026-09-10',
    source: 'Grain Marketing Board (GMB)',
    unit: 'per tonne',
  },
  {
    produce: 'Soyabeans',
    market: 'GMB Producer Price',
    province: 'Harare',
    location: 'National (floor price)',
    rangeLow: 660.95,
    rangeHigh: 660.95,
    average: 660.95,
    date: '2026-09-10',
    source: 'Grain Marketing Board (GMB)',
    unit: 'per tonne',
  },
  {
    produce: 'Sunflower',
    market: 'GMB Producer Price',
    province: 'Harare',
    location: 'National (floor price)',
    rangeLow: 826.19,
    rangeHigh: 826.19,
    average: 826.19,
    date: '2026-09-10',
    source: 'Grain Marketing Board (GMB)',
    unit: 'per tonne',
  },
  {
    produce: 'Wheat',
    market: 'GMB Producer Price',
    province: 'Harare',
    location: 'National (floor price)',
    rangeLow: 531.93,
    rangeHigh: 531.93,
    average: 531.93,
    date: '2026-09-10',
    source: 'Grain Marketing Board (GMB)',
    unit: 'per tonne',
  },
]
